import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import 'recording_service.dart';
import 'vehicle_profile_service.dart';
import '../data/dtc_database.dart';

/// Service for generating diagnostic reports in PDF format
class ReportService {
  static final ReportService _instance = ReportService._internal();
  factory ReportService() => _instance;
  ReportService._internal();

  final _dtcDatabase = DTCDatabase();
  final _dateFormat = DateFormat('yyyy-MM-dd HH:mm');

  /// Generate a comprehensive diagnostic report
  Future<Uint8List> generateReport({
    required SessionDetails session,
    VehicleProfile? vehicle,
    String? technicianName,
    String? shopName,
    String? notes,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(context, shopName),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildTitle(),
          pw.SizedBox(height: 20),
          if (vehicle != null) _buildVehicleInfo(vehicle),
          pw.SizedBox(height: 20),
          _buildSessionInfo(session, technicianName),
          pw.SizedBox(height: 20),
          _buildDTCSection(session.dtcs),
          if (session.dataPoints.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            _buildDataSummary(session.dataPoints),
          ],
          if (notes != null && notes.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            _buildNotesSection(notes),
          ],
          pw.SizedBox(height: 30),
          _buildSignatureSection(technicianName),
        ],
      ),
    );

    return pdf.save();
  }

  /// Generate a quick DTC-only report
  Future<Uint8List> generateDTCReport(List<RecordedDTC> dtcs, {VehicleProfile? vehicle}) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          _buildTitle(title: 'DTC Report'),
          pw.SizedBox(height: 20),
          if (vehicle != null) _buildVehicleInfo(vehicle),
          pw.SizedBox(height: 20),
          _buildDTCSection(dtcs),
        ],
      ),
    );

    return pdf.save();
  }

  /// Save report to file and return path
  Future<String> saveReport(Uint8List pdfBytes, String filename) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/OpenDiag Reports/$filename.pdf');
    await file.parent.create(recursive: true);
    await file.writeAsBytes(pdfBytes);
    return file.path;
  }

  pw.Widget _buildHeader(pw.Context context, String? shopName) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(width: 1, color: PdfColors.grey300)),
      ),
      padding: const pw.EdgeInsets.only(bottom: 10),
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            shopName ?? 'OpenDiag',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue800,
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(width: 1, color: PdfColors.grey300)),
      ),
      padding: const pw.EdgeInsets.only(top: 10),
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by OpenDiag',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
          pw.Text(
            _dateFormat.format(DateTime.now()),
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTitle({String title = 'Vehicle Diagnostic Report'}) {
    return pw.Center(
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 24,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
    );
  }

  pw.Widget _buildVehicleInfo(VehicleProfile vehicle) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Vehicle Information',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              pw.Expanded(child: _buildInfoRow('VIN', vehicle.vin ?? 'N/A')),
              pw.Expanded(child: _buildInfoRow('Year', vehicle.year?.toString() ?? 'N/A')),
            ],
          ),
          pw.SizedBox(height: 5),
          pw.Row(
            children: [
              pw.Expanded(child: _buildInfoRow('Make', vehicle.make ?? 'N/A')),
              pw.Expanded(child: _buildInfoRow('Model', vehicle.model ?? 'N/A')),
            ],
          ),
          if (vehicle.engine != null || vehicle.transmission != null) ...[
            pw.SizedBox(height: 5),
            pw.Row(
              children: [
                pw.Expanded(child: _buildInfoRow('Engine', vehicle.engine ?? 'N/A')),
                pw.Expanded(child: _buildInfoRow('Transmission', vehicle.transmission ?? 'N/A')),
              ],
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _buildSessionInfo(SessionDetails session, String? technician) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Session Details',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              pw.Expanded(
                child: _buildInfoRow('Start Time', _dateFormat.format(session.session.startTime)),
              ),
              pw.Expanded(
                child: _buildInfoRow(
                  'End Time',
                  session.session.endTime != null
                      ? _dateFormat.format(session.session.endTime!)
                      : 'In Progress',
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 5),
          pw.Row(
            children: [
              pw.Expanded(
                child: _buildInfoRow(
                  'Duration',
                  session.session.duration != null
                      ? _formatDuration(session.session.duration!)
                      : 'N/A',
                ),
              ),
              if (technician != null)
                pw.Expanded(child: _buildInfoRow('Technician', technician)),
            ],
          ),
          if (session.session.mileage != null) ...[
            pw.SizedBox(height: 5),
            _buildInfoRow('Mileage', '${session.session.mileage} km'),
          ],
        ],
      ),
    );
  }

  pw.Widget _buildDTCSection(List<RecordedDTC> dtcs) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Diagnostic Trouble Codes',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        if (dtcs.isEmpty)
          pw.Container(
            padding: const pw.EdgeInsets.all(15),
            decoration: pw.BoxDecoration(
              color: PdfColors.green50,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              children: [
                pw.Text('✓ ', style: pw.TextStyle(color: PdfColors.green800, fontWeight: pw.FontWeight.bold)),
                pw.Text('No diagnostic trouble codes found', style: const pw.TextStyle(color: PdfColors.green800)),
              ],
            ),
          )
        else
          ...dtcs.map((dtc) => _buildDTCCard(dtc)),
      ],
    );
  }

  pw.Widget _buildDTCCard(RecordedDTC dtc) {
    final definition = _dtcDatabase.lookup(dtc.code);

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(
          color: dtc.isPending ? PdfColors.orange300 : PdfColors.red300,
        ),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                dtc.code,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: dtc.isPending ? PdfColors.orange800 : PdfColors.red800,
                ),
              ),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: pw.BoxDecoration(
                  color: dtc.isPending ? PdfColors.orange100 : PdfColors.red100,
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  dtc.isPending ? 'Pending' : 'Stored',
                  style: pw.TextStyle(
                    fontSize: 9,
                    color: dtc.isPending ? PdfColors.orange800 : PdfColors.red800,
                  ),
                ),
              ),
            ],
          ),
          if (definition != null) ...[
            pw.SizedBox(height: 6),
            pw.Text(definition.description),
            if (definition.cause != null) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                'Cause: ${definition.cause}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              ),
            ],
            if (definition.possibleFixes.isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                'Suggested Fixes:',
                style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
              ),
              ...definition.possibleFixes.take(3).map(
                (fix) => pw.Padding(
                  padding: const pw.EdgeInsets.only(left: 10, top: 2),
                  child: pw.Text('• $fix', style: const pw.TextStyle(fontSize: 10)),
                ),
              ),
            ],
          ] else
            pw.Text(
              'No detailed information available for this code.',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
        ],
      ),
    );
  }

  pw.Widget _buildDataSummary(List<RecordedDataPoint> dataPoints) {
    // Group data by PID and calculate statistics
    final pidStats = <String, _PIDStats>{};

    for (final point in dataPoints) {
      if (point.value == null) continue;

      final key = point.pidName;
      if (!pidStats.containsKey(key)) {
        pidStats[key] = _PIDStats(
          name: point.pidName,
          unit: point.unit ?? '',
          values: [],
        );
      }
      pidStats[key]!.values.add(point.value!);
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Live Data Summary',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _buildTableHeader('Parameter'),
                _buildTableHeader('Min'),
                _buildTableHeader('Max'),
                _buildTableHeader('Avg'),
                _buildTableHeader('Unit'),
              ],
            ),
            ...pidStats.values.map((stats) => pw.TableRow(
              children: [
                _buildTableCell(stats.name),
                _buildTableCell(stats.min.toStringAsFixed(1)),
                _buildTableCell(stats.max.toStringAsFixed(1)),
                _buildTableCell(stats.avg.toStringAsFixed(1)),
                _buildTableCell(stats.unit),
              ],
            )),
          ],
        ),
        pw.SizedBox(height: 5),
        pw.Text(
          'Total data points recorded: ${dataPoints.length}',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
        ),
      ],
    );
  }

  pw.Widget _buildNotesSection(String notes) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Technician Notes',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          width: double.infinity,
          decoration: pw.BoxDecoration(
            color: PdfColors.yellow50,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Text(notes),
        ),
      ],
    );
  }

  pw.Widget _buildSignatureSection(String? technician) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.end,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(
              width: 200,
              height: 40,
              decoration: const pw.BoxDecoration(
                border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey400)),
              ),
            ),
            pw.SizedBox(height: 5),
            pw.Text(
              technician ?? 'Technician Signature',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
            pw.SizedBox(height: 3),
            pw.Text(
              _dateFormat.format(DateTime.now()),
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          '$label: ',
          style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
      ],
    );
  }

  pw.Widget _buildTableHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  pw.Widget _buildTableCell(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 10),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  String _formatDuration(Duration duration) {
    final hours = duration.inHours;
    final minutes = duration.inMinutes % 60;
    final seconds = duration.inSeconds % 60;

    if (hours > 0) {
      return '${hours}h ${minutes}m ${seconds}s';
    } else if (minutes > 0) {
      return '${minutes}m ${seconds}s';
    } else {
      return '${seconds}s';
    }
  }
}

class _PIDStats {
  final String name;
  final String unit;
  final List<double> values;

  _PIDStats({
    required this.name,
    required this.unit,
    required this.values,
  });

  double get min => values.isEmpty ? 0 : values.reduce((a, b) => a < b ? a : b);
  double get max => values.isEmpty ? 0 : values.reduce((a, b) => a > b ? a : b);
  double get avg => values.isEmpty ? 0 : values.reduce((a, b) => a + b) / values.length;
}
